#!/usr/bin/env python
"""
WSGI config for djangoTest project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/1.6/howto/deployment/wsgi/
"""

import os
import sys
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "djangoTest.settings")
sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR']))


from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()
